### ISSUE TITLE
Crash: ATLConversationViewController, self.collectionView performBatchUpdates!!!

### ISSUE THREAD

**Issue by Ashif22khan** [layerhq/Atlas-iOS#1164]
Whenever two participants are exchanging messages rapidly (like 6-7 messages per 5 seconds), this crash happens, The detail of the crash log can be found here. #1159

After spending a lot of time on this I realised that somehow the section count are changing concurrently e.g. at the start of the batch updates the section count is say 60, some how during the batch updates, while exchanging messages rapidly, this count changes (i.e. 62) which triggers NSInternalInconsistencyException.

May be the data source is being updated from multiple sources, I think all the changes to the datasource of collectionView should be done using one single queue of changes.

As a fix to avoid the crash I have enclosed the performBatchUpdate call inside a "@try, @catch", However if anybody can suggest me on how to fix the issue, that would be great help......

**Comment by Ashif22khan** [comment]
@kmahal Can you please guide me on this. Thanks.

**Comment by williamtwilson** [comment]
I'm also experiencing this.

**Comment by Ashif22khan** [comment]
@williamtwilson currently there are no updates on this, from atlas I am still awaiting their reply, I had to enclose my performBatchUpdate call inside a "@try, @catch", hope it helps.
But I don't it is the right solution.....

**Comment by kcoleman731** [comment]
Hi @Ashif22khan and @williamtwilson can you guys tell me the atlas version you are using?

**Comment by Ashif22khan** [comment]
Hi @kcoleman731 I am using Atlas 1.0.13.

**Comment by pthrasher** [comment]
@kcoleman731 I'm also experiencing this. I'm using Atlas 1.0.22

The best way I've found to repro is to quickly open up an app from completely closed, and very quickly after starting the application, attempt to send a message.

**Comment by kcoleman731** [comment]
@Ashif22khan this was most certainly an issue with 1.0.13. The underlying issue is actually with the LayerKit version which is an Atlas dependency. 

@pthrasher Thank you for the heads up on `1.0.22`. I'll try your repro today and see if I can catch it. Any other specifics you can give would be helpful.

**Comment by pthrasher** [comment]
@kcoleman731 So... a bit more details...

1. When atlas asks me for a participant record I return a new instance of `ZMUser` (unless there was already one existing) -- This has all the information blank except for userID. I then go hit my server to backfill the data.
2. When sending a message for the first time, the authenticatedUser has not yet been requested. So, end user hits `send`, atlas asks me for the user record, I provide it, and I think what's happening is that when the table is doing a batched update, I get data back on that user record, and call `reloadData`

I think that's what triggers this error for me.

**Comment by kcoleman731** [comment]
@pthrasher yep that will be the issue. You never want to call `reloadData` directly. We have an explicit public method which allows you to trigger a cell reload that is meant for these types of situations. 

```
- (void)reloadCellForMessage:(LYRMessage *)message;
```

Can you switch over to using that method and let me know if it solves your issue?

**Comment by kcoleman731** [comment]
@mailyan unfortunately that scenario doesn't shed a bunch of light on the problem. Are you using the latest Atlas?

**Comment by woutergoossens** [comment]
Having the same problem. 

2016-09-04 23:50:30.970 MerciMerci[2933:1013522] *** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UICollectionView.m:4609
2016-09-04 23:50:30.970 MerciMerci[2933:1013522] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (4) must be equal to the number of sections contained in the collection view before the update (4), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).'
*** First throw call stack:
(0x18157adb0 0x180bdff80 0x18157ac80 0x181f00154 0x186f2ad38 0x186f2e464 0x186f2e2e0 0x1868cc2a4 0x1006bdcf8 0x100cdf038 0x102ca5a3c 0x102cb6040 0x102ca5a3c 0x102cab4e4 0x181530d50 0x18152ebb8 0x181458c50 0x182d40088 0x186746088 0x10003d64c 0x180ff68b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by magneticrob** [comment]
@mailyan I'm trying to do the same thing and am experiencing the same crash, with the latest Atlas and latest Layer. Did you ever find a solution for this?

**Comment by magneticrob** [comment]
Just a quick update, I managed to fix it. Just integrate the pull request below. 

It seems to have failed the CI so it's not in Atlas yet, but I'm not experiencing the crash since.

https://github.com/layerhq/Atlas-iOS/pull/1328/commits/7a28965f2c98a7c4818d5c86ea97da19661aef19

**Comment by tgrf** [comment]
Problem still exists in the most recent pod of Atlas, `1.1.2`. We've got the same exception, when quickly typing messages.
`2017-10-27 17:06:47.890229+0200 App[1041:296570] *** Assertion failure in -[ATLConversationCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3694.4.18/UICollectionView.m:5997
2017-10-27 17:13:53.856979+0200 App[1041:296570] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (85) must be equal to the number of sections contained in the collection view before the update (85), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).'`
