### ISSUE TITLE
Keyboard offset when displayed inside UITabBarController

### ISSUE THREAD

**Issue by mkoppanen** [layerhq/Atlas-iOS#250]
Hello,

I am having a strange issue when displaying ATLConversationViewController from a ATLConversationListViewController that is contained inside UITabBarController. I haven't debugged further yet but it seems that keyboard is offset based on the tab bar area:

https://www.dropbox.com/s/a46domzq74oospd/Screenshot%202015-02-27%2011.04.46.png?dl=0
(see the white space at the bottom of the screen)

I will debug this further tonight but if you got any pointers where to look that would be immensely helpful.

**Comment by kcoleman731** [comment]
Hi @mkoppanen I'd be happy to look into this for you. Will get back to you shortly with my findings.

**Comment by kcoleman731** [comment]
Hi @mkoppanen 

I was just able to have a look at your issue. Can you tell me what version of iOS you are seeing this on?

On an iOS 8 device, I have an `ATLConversationListViewController` setup as the root view controller of a `UINavigationController`. The NavController is the only view controller presented by a `UITabBarController`. When I tap on a conversation, I am presenting the `ATLConversationViewController` and setting the `tapBar.hidden` property to true. Everything works as expected in this case.

**Comment by mkoppanen** [comment]
@kcoleman731,

in my case I have UINavigationController on top of UITabBarController and the tab bar controller has the ATLConversationListViewController from which i use:

````
        let conversationVC = ConversationViewController(layerClient: self.layerClient)
        conversationVC.conversation = conversation

        self.navigationController?.pushViewController(conversationVC, animated: true)
````
to display the ATLConversationViewController

**Comment by kcoleman731** [comment]
Hi @mkoppanen 

If I understand you correctly, you are doing the following. 

```
  ATLSampleConversationListViewController *controller = [ATLSampleConversationListViewController conversationListViewControllerWithLayerClient:(LYRClient *)layerClient];
    controller.view.backgroundColor = [UIColor whiteColor];
    
    UITabBarController *tabController = [[UITabBarController alloc] init];
    tabController.viewControllers = @[controller];
    
    UINavigationController *rootViewController = [[UINavigationController alloc] initWithRootViewController:tabController];
    
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.rootViewController = rootViewController;
    [self.window makeKeyAndVisible];
```

If so, this still behaves as expected on our side. If you share a gist of how you are setting up you view controller stack, perhaps I can be more helpful.

**Comment by mkoppanen** [comment]
@kcoleman731,

I am doing most of the basic wiring of controllers via storyboards but looking at the code that seems roughly like the same order I am doing things. However, I've been banging my head against this for a while now and it seems like there might be something else going wrong within my project. I am noticing the following now as well:

https://www.dropbox.com/s/8gyzmg65zscb1mb/Screenshot%202015-02-28%2014.53.53.png?dl=0

See how "Yesterday" seems to be completely misaligned within the cell. I'll try to have some time to create an empty project and reproduce this issue with code that I can share with you. At the moment I am retrofitting Atlas into a fairly large project and it might be that things are going wrong somewhere else.

**Comment by mkoppanen** [comment]
@kcoleman731,

I figured out that the text was misaligned due to missing name. I haven't had time to create a complete project yet but I set the conversation list controller as the rootview controller in my navigation controller and recorded the keyboard behaviour. (I have seriously no idea what's going on here): 

https://www.dropbox.com/s/sewsg64hlam8t8j/atlas-ios-keyboard.mov?dl=0

I am showing the conversation list as the rootviewcontroller for a navigation controller using storyboards and using pushviewcontroller manually to show the conversationcontroller. As far as I know I am not doing anything funny here. iOS8

**Comment by kmahal** [comment]
HI @mkoppanen I set up an application with your set up using storyboard, and couldn't reproduce the issue myself, but I believe the issue is around `keyboardDismissMode` which is set to `UIScrollViewKeyboardDismissModeInteractive`, which allows the user to drag the keyboard up and down as they pan in the collectionView.

Here's an article I found that should point you in the right direction: http://www.krisdigital.com/imessage-style-keyboard-ios-8 , where someone had the same issue you are having.

Specifically look at the comments for the method `(CGSize)intrinsicContentSize` where they discuss how to fix this in iOS8 without the alternative way listed in the main article.  Meanwhile we'll work on our side to integrate this fix with Atlas for the future so it works correctly on all OS versions.

Regards,
Kabir

**Comment by mkoppanen** [comment]
Hello,

I finally managed to figure this out and the error is completely at my end. I created an empty project and Atlas works exactly as expected. Then I started debugging potential things that I am doing in my app that could affect it and eventually found the culprit:

I am using https://github.com/hackiftekhar/IQKeyboardManager/ for some forms in the app and it seems that IQKeyboardManager doesn't play well with Atlas. Disabling the IQKeyboardManager for the view solved my issue.

Thanks for amazing support guys and keep up the good work!

**Comment by chlebta** [comment]
@mkoppanen :+1: you saved my day got same issue and disabling `IQKeyboardManager` for my class solved my issue 
```
    [[IQKeyboardManager sharedManager] disableInViewControllerClass:[ConversationViewController class]];
```

**Comment by Creky** [comment]
I removed IQKeyboardManager, and the gap disappeared! thx @chlebta @mkoppanen !!!

**Comment by tariq235** [comment]
hey @kcoleman731  I wrote all layer architecture in my project like session management, persistence, authentication etc. But nothing is showing in my ATLConversationListViewController.

ConversationListVC has been added in my tabbar initialization with other VC initialization i.e
```
[IVChatListViewController conversationListViewControllerWithLayerClient:self.applicationController.layerClient]
    navigationController = [[IVCustomNavigationController alloc] initWithRootViewController:self.conversationListViewController];
    [tabs addObject:navigationController];

```
How should I refresh all contents after layer authentication ? In your example ATlas messanger code you allocate listVC in presentAuthenticatedLayerSession method. This method will be called on resumeSession or userDidAuthenticateWithLayer notification.

I can't do the same in my app because i have already called conversationListViewControllerWithLayerClient in my app delegate tabbar initialization.

How to refresh ?
