### ISSUE TITLE
How to get number of unread messages in conversation list? 

### ISSUE THREAD

**Issue by vikpower** [layerhq/Atlas-iOS#765]
and to add observer to observe them?

**Comment by chipxsd** [comment]
What exactly do you want to achieve? Display a total number of unread messages or unread message count per conversation?

**Comment by vikpower** [comment]
I would like to show number of unread conversations and unread messages user has. 
Few use cases: badge of unread conversations in tab bar controller or in barbuttonItem

**Comment by chipxsd** [comment]
You can use the `LYRQueryController` with a `LYRQuery` that only fetches messages where `isUnread` is true, this would give you a count of all unread messages.

```objective-c
LYRQuery *query = [LYRQuery queryWithClass:[LYRMessage class]];
query.predicate = [LYRPredicate predicateWithProperty:@"isUnread" operator:LYRPredicateOperatorIsEqualTo value:@(YES)];
LYRQueryController *controller = [self.client queryControllerWithQuery:query];
controller.delegate = self;
```

Your interface has to implement the `queryControllerDidChangeContent:` delegate method. This method will get called every time the unread count will change:
```objective-c
- (void)queryControllerDidChangeContent:(LYRQueryController *)queryController
{
    self.numberOfUnreadMessagesLabel.text = [NSString stringWithFormat:@"%d", queryController.count];
}
```

But if you want to get the number of unread conversations, then you should setup the query with `LYRConversation` instead of `LYRMessage`:

```objective-c
LYRQuery *query = [LYRQuery queryWithClass:[LYRConversation class]];
```

**Comment by petec029** [comment]
I also want to display the count of unread conversations in a tab bar icon and came across this post.  Was surprised to see it closed because I tried it and ran into a few issues.

The  predicate property for unread conversations is hasUnreadMessages not isUnread
LYRQuery *query = [LYRQuery queryWithClass:[LYRConversation class]];
query.predicate = [LYRPredicate predicateWithProperty:@"hasUnreadMessages" operator:LYRPredicateOperatorIsEqualTo value:@(YES)];

So I figured that out and am able to get the count of unread conversations to display on my tab bar. But now I can not get it to update.  The queryControllerDidChangeContent delegate is not firing.

I did set the delegate in the tab bar controller's .h file
@interface G2GTabBarController : UITabBarController <LYRQueryControllerDelegate>

and in the .m file set the delegate to self. see below

    LYRQuery *query = [LYRQuery queryWithClass:[LYRConversation class]];
    query.predicate = [LYRPredicate predicateWithProperty:@"hasUnreadMessages" operator:LYRPredicateOperatorIsEqualTo value:@(YES)];
    LYRQueryController *queryController = [appDelegate.layerClient queryControllerWithQuery:query];
    queryController.delegate = self;


Does the hasUnreadMessages property not trigger queryControllerDidChangeContent delegate?
Or am I missing something else?

**Comment by petec029** [comment]
strange but git hub is not showing the  <LYRQueryControllerDelegate> after the @interface G2GTabBarController : UITabBarController

**Comment by petec029** [comment]
Think I figured it out.  Just needed to persist the queryController as a property of the tab bar class

@property (nonatomic, retain) LYRQueryController *queryController;

**Comment by galu08** [comment]
I use this in SWIFT and works ok !
```swift
func getUnreadMessageCountForConversation(conversation :LYRConversation)-> Int {
        var unreadMessages :Int = 0
        
        var query = LYRQuery(queryableClass: LYRMessage.self)
        // The conversation property is equal to the supplied LYRConversation object.
        var conversationPredicate = LYRPredicate(property: "conversation", predicateOperator: LYRPredicateOperator.IsEqualTo, value: conversation)
        // Messages must be unread
        var unreadPredicate = LYRPredicate(property: "isUnread", predicateOperator: LYRPredicateOperator.IsEqualTo, value: true)
        // Messages must not be sent by the authenticated user
        var userPredicate = LYRPredicate(property: "sender.userID", predicateOperator: LYRPredicateOperator.IsNotEqualTo, value: LayerClient.authenticatedUserID)
        
        query.predicate = LYRCompoundPredicate(type: LYRCompoundPredicateType.And, subpredicates: [conversationPredicate, unreadPredicate, userPredicate])
        
        var error : NSError?
        unreadMessages = Int(LayerClient.countForQuery(query, error: &error))
        println("Unread messages: \(unreadMessages)")
        
        if error == nil{
            return unreadMessages
        } else {
            println("Query failed with error: \(error?.localizedDescription)")
            return 0
        }
    }
```
