### ISSUE TITLE
Crash displaying conversation after sending an image. "CALayer bounds contains NaN"

### ISSUE THREAD

**Issue by dippigu** [layerhq/Atlas-iOS#823]
After creating and sending an image as an LYRMessage, any attempts to load the conversation crash with the following:
<code>
2015-05-11 17:27:53.002 mediBuzz[3172:596731] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [0 nan; 375 nan]'
</code>

Gist of creating and sending message:
https://gist.github.com/dippigu/f0992ffcb06e5d3c1689

**Comment by dippigu** [comment]
Further investigation shows that the crash happens when dequeueing the <code>ATLConversationCollectionViewFooter</code> at line 290 in <code>ATLConversationViewController.m</code>, <code>ATLConversationCollectionViewFooter *footer = [self.collectionView dequeueReusableSupplementaryViewOfKind:kind withReuseIdentifier:ATLConversationViewFooterIdentifier forIndexPath:indexPath];</code>.

**Comment by kmahal** [comment]
@dippigu Your gist indicates you are sharing a custom `LYRMessage`, but using `ATLMIMETypeImagePNG`, an Atlas defined type.  This will not work unfortunately, since for every image sent through Atlas it actually sends 3 parts over, the full size image, a preview thumb, and the sizing information.  You can fix this in 2 ways: 1. create a custom `MIMEType` for your image, which will require a custom `UICollectionViewCell` that adheres to the `ATLMessagePresenting` protocol, as well as implementing a few delegate Atlas delegate methods for registering your cell and `reuseIdentifier`.  2. Use Atlas natively to send your message by using an `ATLMediaAttachment`.  Using `+ (instancetype)mediaAttachmentWithImage:(UIImage *)image metadata:(NSDictionary *)metadata thumbnailSize:(NSUInteger)thumbnailSize` you can allocate an instance, and add it to the `ATLMessageInputToolbar` instance of the `ATLConversationViewController`.  This way it will handle sending over the image for you, along with it's sizing and thumbnail view.

**Comment by dippigu** [comment]
@kmahal Thanks for the update. That is indeed the problem. I've rewritten the functionality using your option 2, and now wonder if there is a way to control the size of the image displayed in the conversation once it has been sent?  Or would this mean reverting to option 1 and using a custom <code>MIMEType</code> and custom <code>UICollectionViewCell</code>?

**Comment by kmahal** [comment]
@dippigu I just looked into it, and it's almost possible but not quite, so for now option 1 is the only way.  I'll put this request in our backlog though and should have something out in a decent timetable.  I'll update you with it's progress.  Thanks again for the input!

**Comment by dippigu** [comment]
@kmahal Any rough idea on that timescale? I'm on vacation in a few days until the end of May. Is it likely to be done before I return, or should I spend the time now on working around it and building my own custom cells?

**Comment by kmahal** [comment]
@dippigu Just looked into it, and it will take a little bit of work to accomplish.  I think by end of May is reasonable but cannot guarantee anything a date unfortunately.  What are some use cases that you would want to customize the size?  I imagine width is probably the main factor.  As a friendly reminder, Atlas is an open sourced project, and we are open to pull requests with feature requests too :)

**Comment by kmahal** [comment]
@dippigu I'm going to close this one out, feel free to open up a new issue with the request of custom sizing parameters.
