### ISSUE TITLE
Option to use Custom Table/CollectionViewCells which defined via NIB/StoryBoard

### ISSUE THREAD

**Issue by oferRounds** [layerhq/Atlas-iOS#847]
As far as I see, the API does not support it.

**Comment by maju6406** [comment]
Have you looked at the new Custom Payloads section in the docs?
https://developer.layer.com/docs/atlas#custom-payload
You should be able to use a nib for a custom cell

**Comment by oferRounds** [comment]
I see only a way to register a custom cell, which is not initialized from a nib. 

As when using a cell like this, the tableView's method  ```registerNib:forCellReuseIdentifier:``` should be used (instead of the  ```registerClass:forCellReuseIdentifier:```)

**Comment by kmahal** [comment]
@oferRounds Apologies for the late response. You can register the `nib` yourself as both the `tableView` and `collectionView` are public properties of `ATLConversationListViewController` and `ATLConversationViewController` respectively.  Since both controller ask for reuse identifiers in the data source, you can then pass back the identifier it was registered with.

**Comment by oferRounds** [comment]
@kmahal now it's me who apologise - sorry for not being available.
I'll try your solution, thanks!
