### ISSUE TITLE
Delivery status of messages between blocked participants

### ISSUE THREAD

**Issue by dippigu** [layerhq/Atlas-iOS#967]
In the situation where I have two participants chatting to each other and then one blocks the other, all subsequent messages sent by either participants appear to send and return the status of <code>LYRRecipientStatusDelivered</code>.

It would be preferable to return a status of <code>LYRRecipientStatusPending</code> for messages between participants where a block policy is in place, as these messages are not actually delivered.

**Comment by kmahal** [comment]
@dippigu This is left up to the developer to manage.  When creating a `LYRPolicy` with type `LYRPolicyTypeBlock`, the policy is effective one way.  If user A blocks user B, any messages from user B to user A will not go through.  However since user B has not blocked user A, messages can still be delivered from user A to user B.  You can craft an experience around this knowledge, including checking your client''s block policies and managing receipts based on conditional factors.
