### ISSUE TITLE
ATLAddressBarViewController.h not found in Atlas.h 

### ISSUE THREAD

**Issue by nishantdongare** [layerhq/Atlas-iOS#974]
I am facing this issue in atlas.h file. 
![screen shot 2015-09-19 at 6 44 03 pm](https://cloud.githubusercontent.com/assets/9926475/9977180/d439b8aa-5f1b-11e5-9460-2fe2351e7dfe.png)
![screen shot 2015-09-19 at 6 53 29 pm](https://cloud.githubusercontent.com/assets/9926475/9977182/d570fcd8-5f1b-11e5-93f7-3d4282fb68ad.png)

**Comment by maju6406** [comment]
The Layer-Parse-iOS-Swift-Example was created by a third party. You'll need to reach out to them for support on this issue https://github.com/kwkhaw/Layer-Parse-iOS-Swift-Example.

**Comment by ksylvest** [comment]
@maju6406 I experienced the same issue when integrating Atlas into my own project. I created a brand new Xcode project (only pods are Atlas and LayerKit) and uploaded it here: http://cl.ly/3l2Y3x1Z1D15. 

Other pods are fine. What's the preferred way to import Atlas (`#import <Atlas/Atlas.h>`)? Is this due to  the Atlas pod's headers all living in directories (i.e. /Controllers /Models, /Protocols, ...)?
